 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author admin
 */
public class Loader12 extends javax.swing.JFrame {
    
     public Loader12() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/lmslogo11.png")).getImage();
        this.setIconImage(icon);
      
        startLoading();
    }

    private void startLoading() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                      LoadingValue.setText(i + "%");
                    try {
                        Thread.sleep(50); // Simulate loading time
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                    LoadingBar.setValue(i);
                      updateLoadingText(i);
                
                if (i < 100) {
                        LoadingBar.setForeground(new Color(102, 153, 255));
                    } else {
                        LoadingBar.setForeground(UIManager.getColor("ProgressBar.foreground"));
                    }
            }
                dispose();
                new LoginPage().setVisible(true);
            }
        });
        t.start();
    }
    
    private void updateLoadingText(int progress) {
        if (progress == 0) {
            LoadingName.setText("Turning on Modules...");
        } else if (progress == 20) {
            LoadingName.setText("Loading on Modules...");
        } else if (progress == 35) {
            LoadingName.setText("Connecting to Database...");
        } else if (progress == 60) {
            LoadingName.setText("Connection Successful...");
        } else if (progress == 70) {
            LoadingName.setText("Launching Application...");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LoadingValue = new javax.swing.JLabel();
        LoadingName = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 30, 20));

        LoadingName.setBackground(new java.awt.Color(255, 255, 255));
        LoadingName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LoadingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 200, 20));

        LoadingBar.setForeground(new java.awt.Color(102, 153, 255));
        LoadingBar.setBorderPainted(false);
        jPanel1.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 430, 9));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 310, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RYW icons/ezgif.com-gif-maker (4).gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -90, 710, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Library_Management_System_v2\\src\\images\\gbg.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 610, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loader12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loader12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loader12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loader12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
     
            new Loader12().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingName;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
